### ISSUE TITLE
Clubhouse API V2

### ISSUE THREAD

**Issue by camilleacey** [mikkelson/clubhouse-php#1]
I just wanted to let you know that we've released [Clubhouse API V2](https://clubhouse.io/api/rest/v2/). While V1 will continue to be supported, V2 exposes endpoints for several new features such as Teams, Milestones, and Categories.

**Comment by mikkelson** [comment]
@camilleacey Marking your comment resolved as I've jumped from V1 to V3 and moved repo: https://github.com/mikkelson/shortcut-php

**Comment by mikkelson** [comment]
@camilleacey Marking your comment resolved as I've jumped from V1 to V3 and moved repo: https://github.com/mikkelson/shortcut-php
